### ISSUE TITLE
Finalize meta pages

### ISSUE THREAD

**Issue by kulla** [kulla/mfnf-analysis1-print-2018#1]
Can you finalize the meta pages and inform me when you are ready? Please add the sentence "Diese Auflage ist ein Projekt des Serlo Education e.V. und der Fachschaften Mathematik, Physik und Informatik der Ludwig-Maximilians-Universität München."

**Comment by elbotho** [comment]
---
![image](https://user-images.githubusercontent.com/1258870/37977667-82404f20-31e4-11e8-8537-b16a2e8dfe26.png)
---

@kulla this is the place, right?
I also updated the date to april.
Are there any other changes I did not think about?

**Comment by kulla** [comment]
@elbotho That's all right! Those are all changes.

**Comment by elbotho** [comment]
@kulla sorry for the delay.

Here is the new printable cover with a 23mm spine again:
[180329_cover_print_23mm.pdf](https://github.com/kulla/mfnf-analysis1-lmu-print2018/files/1859429/180329_cover_print_23mm.pdf)
