### ISSUE TITLE
Decide which improvements shall be made in the germanwide publication

### ISSUE THREAD

**Issue by kulla** [kulla/mfnf-analysis1-print-2018#21]

**Comment by elbotho** [comment]
I think it's still a problem that some graphics basically don't work at all.
Could we remove them instead?
Or could we get the authors involved to change the most critical ones?

**Comment by kulla** [comment]
Unfortunatetely the pdf export doesn't work currently. I will see on sunday what I can do...

**Comment by kulla** [comment]
All necessary issues are now in https://github.com/kulla/mfnf-analysis1-print-2018/milestone/1
