### ISSUE TITLE
Drucksofa als Druck und Vertrieb einfügen

### ISSUE THREAD

**Issue by kulla** [kulla/mfnf-analysis1-print-2018#34]

**Comment by elbotho** [comment]
do you know to what already?

**Comment by kulla** [comment]
@elbotho no, I have a phone call today about this issue.

**Comment by kulla** [comment]
Drucksofa einfügen in Druck & Vertrieb:

    == Druck und Vertrieb ==
    Drucksofa UG (haftungsbeschränkt)

    Flaschenhofstr. 14a
    90402 Nürnberg

**Comment by kulla** [comment]
Duplicate of #45, old issue...
