### ISSUE TITLE
Add price to back cover

### ISSUE THREAD

**Issue by kulla** [kulla/mfnf-analysis1-print-2018#44]
I have changed the cover. However I used gimp for it :smile: The price needs to be added to the back cover:

![screenshot from 2018-06-26 08-46-31](https://user-images.githubusercontent.com/1327215/41894136-43cf47b0-791e-11e8-846f-6f7469ebac9e.png)

**Comment by elbotho** [comment]
The `cover.pdf` in this repo is not current.

What width does the back have for the drucksofa version? 21,5 or 21,25 something else?
Alternatively you could also send me/update the current version. Thanks!

**Comment by kulla** [comment]
Yes `cover.pdf` needs to be updated. The size `337 × 241 mm` is right.
