### ISSUE TITLE
Update impressum

### ISSUE THREAD

**Issue by kulla** [kulla/mfnf-analysis1-print-2018#45]
In the Indesign template the following needs to be added ("Druckerei und Buchbinderei"):

![screenshot from 2018-06-25 21-22-31](https://user-images.githubusercontent.com/1327215/41871048-0c2bc2f8-78be-11e8-80a6-057e827d5db7.png)

**Comment by elbotho** [comment]
@kulla according to your screenshot there are other changes to the Imprint (text or order) 
(the link to serlo above the Projektleitung is new)
Could you provide me with a current pdf or complete screenshot?

**Comment by kulla** [comment]
Its important that the following text is added:

![screenshot from 2018-08-30 15-34-28](https://user-images.githubusercontent.com/1327215/44855061-81439180-ac6a-11e8-94fd-07ea3eb734f5.png)

Please add this between "Layout und Umschlaggestaltung" and "Titelfoto".

The domain "serlo.org" can be added after Serlo Education e.V. like "kulla.me" or "botho.cc", i.e "Serlo Education e.V. | serlo.org". This however is only a suggestion.

**Comment by elbotho** [comment]
@kulla Should "und der Fachschaften Mathematik, Physik und Informatik der Ludwig-Maximilians-Universität München." still be in there?

**Comment by kulla** [comment]
@elbotho Yes, as long as we use the logo of the LMU we need this addition.
