### ISSUE TITLE
Update page of Wikimedia

### ISSUE THREAD

**Issue by kulla** [kulla/mfnf-analysis1-print-2018#47]
- [x] "dem" vor Wikimedia Deutschland löschen
- [x] "F" in "Freies Wissen" groß schreiben
- [x] Logo anpassen ->[Logo der Wikimedia Deutschland]( https://commons.wikimedia.org/wiki/File:Wikimedia_Deutschland-Logo.svg?uselang=de ) benutzen [Link zu SVG-Version](https://upload.wikimedia.org/wikipedia/commons/e/e8/Wikimedia_Deutschland-Logo.svg)

**Comment by elbotho** [comment]
@kulla Was meinst du "Freie Bildung" dann im Zitat unten auch groß?

**Comment by kulla** [comment]
@elbotho Nein, nur "freies Wissen -> Freies Wissen" ("freie Bildung" bleibt)
